/**
 * DropBuddies API
 * An API for Dropbuddies on-demand delivery service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@dropbuddies.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.dropbuddies.core.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Acceptor
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T00:00:58.629+01:00")
public class Acceptor   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("created_on")
  private Long createdOn = null;

  @SerializedName("updated_on")
  private Long updatedOn = null;

  @SerializedName("accepted_on")
  private Long acceptedOn = null;

  @SerializedName("approved_on")
  private Long approvedOn = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("dropbuddy_id")
  private String dropbuddyId = null;

  @SerializedName("order_id")
  private String orderId = null;

  @SerializedName("price_suggestion")
  private Double priceSuggestion = null;

  public Acceptor id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Acceptor createdOn(Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Long createdOn) {
    this.createdOn = createdOn;
  }

  public Acceptor updatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Get updatedOn
   * @return updatedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
  }

  public Acceptor acceptedOn(Long acceptedOn) {
    this.acceptedOn = acceptedOn;
    return this;
  }

   /**
   * Get acceptedOn
   * @return acceptedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAcceptedOn() {
    return acceptedOn;
  }

  public void setAcceptedOn(Long acceptedOn) {
    this.acceptedOn = acceptedOn;
  }

  public Acceptor approvedOn(Long approvedOn) {
    this.approvedOn = approvedOn;
    return this;
  }

   /**
   * Get approvedOn
   * @return approvedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getApprovedOn() {
    return approvedOn;
  }

  public void setApprovedOn(Long approvedOn) {
    this.approvedOn = approvedOn;
  }

  public Acceptor status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Acceptor dropbuddyId(String dropbuddyId) {
    this.dropbuddyId = dropbuddyId;
    return this;
  }

   /**
   * Get dropbuddyId
   * @return dropbuddyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDropbuddyId() {
    return dropbuddyId;
  }

  public void setDropbuddyId(String dropbuddyId) {
    this.dropbuddyId = dropbuddyId;
  }

  public Acceptor orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public Acceptor priceSuggestion(Double priceSuggestion) {
    this.priceSuggestion = priceSuggestion;
    return this;
  }

   /**
   * Get priceSuggestion
   * @return priceSuggestion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPriceSuggestion() {
    return priceSuggestion;
  }

  public void setPriceSuggestion(Double priceSuggestion) {
    this.priceSuggestion = priceSuggestion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Acceptor acceptor = (Acceptor) o;
    return Objects.equals(this.id, acceptor.id) &&
        Objects.equals(this.createdOn, acceptor.createdOn) &&
        Objects.equals(this.updatedOn, acceptor.updatedOn) &&
        Objects.equals(this.acceptedOn, acceptor.acceptedOn) &&
        Objects.equals(this.approvedOn, acceptor.approvedOn) &&
        Objects.equals(this.status, acceptor.status) &&
        Objects.equals(this.dropbuddyId, acceptor.dropbuddyId) &&
        Objects.equals(this.orderId, acceptor.orderId) &&
        Objects.equals(this.priceSuggestion, acceptor.priceSuggestion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdOn, updatedOn, acceptedOn, approvedOn, status, dropbuddyId, orderId, priceSuggestion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Acceptor {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    acceptedOn: ").append(toIndentedString(acceptedOn)).append("\n");
    sb.append("    approvedOn: ").append(toIndentedString(approvedOn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dropbuddyId: ").append(toIndentedString(dropbuddyId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    priceSuggestion: ").append(toIndentedString(priceSuggestion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

