/**
 * DropBuddies API
 * An API for Dropbuddies on-demand delivery service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@dropbuddies.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.dropbuddies.core.client;

import java.util.Objects;
import com.dropbuddies.core.client.Location;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Order
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T00:00:58.629+01:00")
public class Order   {
  @SerializedName("unique_id")
  private String uniqueId = null;

  @SerializedName("pickup_address")
  private String pickupAddress = null;

  @SerializedName("dropoff_address")
  private String dropoffAddress = null;

  @SerializedName("pickup_location")
  private Location pickupLocation = null;

  @SerializedName("dropoff_location")
  private Location dropoffLocation = null;

  @SerializedName("item_type")
  private String itemType = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("size_fit")
  private String sizeFit = null;

  @SerializedName("request_type")
  private String requestType = null;

  @SerializedName("delivery_type")
  private String deliveryType = null;

  @SerializedName("ownerid")
  private String ownerid = null;

  @SerializedName("owner_type")
  private String ownerType = null;

  @SerializedName("pickup_name")
  private String pickupName = null;

  @SerializedName("pickup_phonenumber")
  private String pickupPhonenumber = null;

  @SerializedName("pickup_email")
  private String pickupEmail = null;

  @SerializedName("recipient_name")
  private String recipientName = null;

  @SerializedName("recipient_phonenumber")
  private String recipientPhonenumber = null;

  @SerializedName("recipient_email")
  private String recipientEmail = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("payment_status")
  private String paymentStatus = null;

  @SerializedName("delivery_status")
  private String deliveryStatus = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("user_delivery_status")
  private String userDeliveryStatus = null;

  @SerializedName("rating_message")
  private String ratingMessage = null;

  @SerializedName("dropbuddy_id")
  private String dropbuddyId = null;

  @SerializedName("promo_code")
  private String promoCode = null;

  @SerializedName("value_of_item")
  private Double valueOfItem = null;

  @SerializedName("rating")
  private Integer rating = null;

  @SerializedName("dropoff_time")
  private Long dropoffTime = null;

  @SerializedName("pickup_time")
  private Long pickupTime = null;

  @SerializedName("pickup_longitude")
  private Double pickupLongitude = null;

  @SerializedName("pickup_latitude")
  private Double pickupLatitude = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("created_on")
  private Long createdOn = null;

  @SerializedName("updated_on")
  private Long updatedOn = null;

  @SerializedName("accepted_on")
  private Long acceptedOn = null;

  @SerializedName("selectDropBuddy")
  private Integer selectDropBuddy = null;

  @SerializedName("allowPriceSuggestion")
  private Integer allowPriceSuggestion = null;

  @SerializedName("cancelled_on")
  private Long cancelledOn = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("suggestedPrice")
  private Double suggestedPrice = null;

  public Order uniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * Get uniqueId
   * @return uniqueId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUniqueId() {
    return uniqueId;
  }

  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }

  public Order pickupAddress(String pickupAddress) {
    this.pickupAddress = pickupAddress;
    return this;
  }

   /**
   * Get pickupAddress
   * @return pickupAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPickupAddress() {
    return pickupAddress;
  }

  public void setPickupAddress(String pickupAddress) {
    this.pickupAddress = pickupAddress;
  }

  public Order dropoffAddress(String dropoffAddress) {
    this.dropoffAddress = dropoffAddress;
    return this;
  }

   /**
   * Get dropoffAddress
   * @return dropoffAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDropoffAddress() {
    return dropoffAddress;
  }

  public void setDropoffAddress(String dropoffAddress) {
    this.dropoffAddress = dropoffAddress;
  }

  public Order pickupLocation(Location pickupLocation) {
    this.pickupLocation = pickupLocation;
    return this;
  }

   /**
   * Get pickupLocation
   * @return pickupLocation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Location getPickupLocation() {
    return pickupLocation;
  }

  public void setPickupLocation(Location pickupLocation) {
    this.pickupLocation = pickupLocation;
  }

  public Order dropoffLocation(Location dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
    return this;
  }

   /**
   * Get dropoffLocation
   * @return dropoffLocation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Location getDropoffLocation() {
    return dropoffLocation;
  }

  public void setDropoffLocation(Location dropoffLocation) {
    this.dropoffLocation = dropoffLocation;
  }

  public Order itemType(String itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Get itemType
   * @return itemType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemType() {
    return itemType;
  }

  public void setItemType(String itemType) {
    this.itemType = itemType;
  }

  public Order description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Order sizeFit(String sizeFit) {
    this.sizeFit = sizeFit;
    return this;
  }

   /**
   * Get sizeFit
   * @return sizeFit
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSizeFit() {
    return sizeFit;
  }

  public void setSizeFit(String sizeFit) {
    this.sizeFit = sizeFit;
  }

  public Order requestType(String requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Get requestType
   * @return requestType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRequestType() {
    return requestType;
  }

  public void setRequestType(String requestType) {
    this.requestType = requestType;
  }

  public Order deliveryType(String deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

   /**
   * Get deliveryType
   * @return deliveryType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(String deliveryType) {
    this.deliveryType = deliveryType;
  }

  public Order ownerid(String ownerid) {
    this.ownerid = ownerid;
    return this;
  }

   /**
   * Get ownerid
   * @return ownerid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerid() {
    return ownerid;
  }

  public void setOwnerid(String ownerid) {
    this.ownerid = ownerid;
  }

  public Order ownerType(String ownerType) {
    this.ownerType = ownerType;
    return this;
  }

   /**
   * Get ownerType
   * @return ownerType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerType() {
    return ownerType;
  }

  public void setOwnerType(String ownerType) {
    this.ownerType = ownerType;
  }

  public Order pickupName(String pickupName) {
    this.pickupName = pickupName;
    return this;
  }

   /**
   * Get pickupName
   * @return pickupName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPickupName() {
    return pickupName;
  }

  public void setPickupName(String pickupName) {
    this.pickupName = pickupName;
  }

  public Order pickupPhonenumber(String pickupPhonenumber) {
    this.pickupPhonenumber = pickupPhonenumber;
    return this;
  }

   /**
   * Get pickupPhonenumber
   * @return pickupPhonenumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPickupPhonenumber() {
    return pickupPhonenumber;
  }

  public void setPickupPhonenumber(String pickupPhonenumber) {
    this.pickupPhonenumber = pickupPhonenumber;
  }

  public Order pickupEmail(String pickupEmail) {
    this.pickupEmail = pickupEmail;
    return this;
  }

   /**
   * Get pickupEmail
   * @return pickupEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPickupEmail() {
    return pickupEmail;
  }

  public void setPickupEmail(String pickupEmail) {
    this.pickupEmail = pickupEmail;
  }

  public Order recipientName(String recipientName) {
    this.recipientName = recipientName;
    return this;
  }

   /**
   * Get recipientName
   * @return recipientName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRecipientName() {
    return recipientName;
  }

  public void setRecipientName(String recipientName) {
    this.recipientName = recipientName;
  }

  public Order recipientPhonenumber(String recipientPhonenumber) {
    this.recipientPhonenumber = recipientPhonenumber;
    return this;
  }

   /**
   * Get recipientPhonenumber
   * @return recipientPhonenumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRecipientPhonenumber() {
    return recipientPhonenumber;
  }

  public void setRecipientPhonenumber(String recipientPhonenumber) {
    this.recipientPhonenumber = recipientPhonenumber;
  }

  public Order recipientEmail(String recipientEmail) {
    this.recipientEmail = recipientEmail;
    return this;
  }

   /**
   * Get recipientEmail
   * @return recipientEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRecipientEmail() {
    return recipientEmail;
  }

  public void setRecipientEmail(String recipientEmail) {
    this.recipientEmail = recipientEmail;
  }

  public Order source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Order paymentStatus(String paymentStatus) {
    this.paymentStatus = paymentStatus;
    return this;
  }

   /**
   * Get paymentStatus
   * @return paymentStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPaymentStatus() {
    return paymentStatus;
  }

  public void setPaymentStatus(String paymentStatus) {
    this.paymentStatus = paymentStatus;
  }

  public Order deliveryStatus(String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
    return this;
  }

   /**
   * Get deliveryStatus
   * @return deliveryStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeliveryStatus() {
    return deliveryStatus;
  }

  public void setDeliveryStatus(String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }

  public Order status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Order userDeliveryStatus(String userDeliveryStatus) {
    this.userDeliveryStatus = userDeliveryStatus;
    return this;
  }

   /**
   * Get userDeliveryStatus
   * @return userDeliveryStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserDeliveryStatus() {
    return userDeliveryStatus;
  }

  public void setUserDeliveryStatus(String userDeliveryStatus) {
    this.userDeliveryStatus = userDeliveryStatus;
  }

  public Order ratingMessage(String ratingMessage) {
    this.ratingMessage = ratingMessage;
    return this;
  }

   /**
   * Get ratingMessage
   * @return ratingMessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRatingMessage() {
    return ratingMessage;
  }

  public void setRatingMessage(String ratingMessage) {
    this.ratingMessage = ratingMessage;
  }

  public Order dropbuddyId(String dropbuddyId) {
    this.dropbuddyId = dropbuddyId;
    return this;
  }

   /**
   * Get dropbuddyId
   * @return dropbuddyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDropbuddyId() {
    return dropbuddyId;
  }

  public void setDropbuddyId(String dropbuddyId) {
    this.dropbuddyId = dropbuddyId;
  }

  public Order promoCode(String promoCode) {
    this.promoCode = promoCode;
    return this;
  }

   /**
   * Get promoCode
   * @return promoCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPromoCode() {
    return promoCode;
  }

  public void setPromoCode(String promoCode) {
    this.promoCode = promoCode;
  }

  public Order valueOfItem(Double valueOfItem) {
    this.valueOfItem = valueOfItem;
    return this;
  }

   /**
   * Get valueOfItem
   * @return valueOfItem
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getValueOfItem() {
    return valueOfItem;
  }

  public void setValueOfItem(Double valueOfItem) {
    this.valueOfItem = valueOfItem;
  }

  public Order rating(Integer rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRating() {
    return rating;
  }

  public void setRating(Integer rating) {
    this.rating = rating;
  }

  public Order dropoffTime(Long dropoffTime) {
    this.dropoffTime = dropoffTime;
    return this;
  }

   /**
   * Get dropoffTime
   * @return dropoffTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDropoffTime() {
    return dropoffTime;
  }

  public void setDropoffTime(Long dropoffTime) {
    this.dropoffTime = dropoffTime;
  }

  public Order pickupTime(Long pickupTime) {
    this.pickupTime = pickupTime;
    return this;
  }

   /**
   * Get pickupTime
   * @return pickupTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPickupTime() {
    return pickupTime;
  }

  public void setPickupTime(Long pickupTime) {
    this.pickupTime = pickupTime;
  }

  public Order pickupLongitude(Double pickupLongitude) {
    this.pickupLongitude = pickupLongitude;
    return this;
  }

   /**
   * Get pickupLongitude
   * @return pickupLongitude
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPickupLongitude() {
    return pickupLongitude;
  }

  public void setPickupLongitude(Double pickupLongitude) {
    this.pickupLongitude = pickupLongitude;
  }

  public Order pickupLatitude(Double pickupLatitude) {
    this.pickupLatitude = pickupLatitude;
    return this;
  }

   /**
   * Get pickupLatitude
   * @return pickupLatitude
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPickupLatitude() {
    return pickupLatitude;
  }

  public void setPickupLatitude(Double pickupLatitude) {
    this.pickupLatitude = pickupLatitude;
  }

  public Order id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Order createdOn(Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Long createdOn) {
    this.createdOn = createdOn;
  }

  public Order updatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Get updatedOn
   * @return updatedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
  }

  public Order acceptedOn(Long acceptedOn) {
    this.acceptedOn = acceptedOn;
    return this;
  }

   /**
   * Get acceptedOn
   * @return acceptedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAcceptedOn() {
    return acceptedOn;
  }

  public void setAcceptedOn(Long acceptedOn) {
    this.acceptedOn = acceptedOn;
  }

  public Order selectDropBuddy(Integer selectDropBuddy) {
    this.selectDropBuddy = selectDropBuddy;
    return this;
  }

   /**
   * Get selectDropBuddy
   * @return selectDropBuddy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSelectDropBuddy() {
    return selectDropBuddy;
  }

  public void setSelectDropBuddy(Integer selectDropBuddy) {
    this.selectDropBuddy = selectDropBuddy;
  }

  public Order allowPriceSuggestion(Integer allowPriceSuggestion) {
    this.allowPriceSuggestion = allowPriceSuggestion;
    return this;
  }

   /**
   * Get allowPriceSuggestion
   * @return allowPriceSuggestion
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAllowPriceSuggestion() {
    return allowPriceSuggestion;
  }

  public void setAllowPriceSuggestion(Integer allowPriceSuggestion) {
    this.allowPriceSuggestion = allowPriceSuggestion;
  }

  public Order cancelledOn(Long cancelledOn) {
    this.cancelledOn = cancelledOn;
    return this;
  }

   /**
   * Get cancelledOn
   * @return cancelledOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCancelledOn() {
    return cancelledOn;
  }

  public void setCancelledOn(Long cancelledOn) {
    this.cancelledOn = cancelledOn;
  }

  public Order quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public Order suggestedPrice(Double suggestedPrice) {
    this.suggestedPrice = suggestedPrice;
    return this;
  }

   /**
   * Get suggestedPrice
   * @return suggestedPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSuggestedPrice() {
    return suggestedPrice;
  }

  public void setSuggestedPrice(Double suggestedPrice) {
    this.suggestedPrice = suggestedPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.uniqueId, order.uniqueId) &&
        Objects.equals(this.pickupAddress, order.pickupAddress) &&
        Objects.equals(this.dropoffAddress, order.dropoffAddress) &&
        Objects.equals(this.pickupLocation, order.pickupLocation) &&
        Objects.equals(this.dropoffLocation, order.dropoffLocation) &&
        Objects.equals(this.itemType, order.itemType) &&
        Objects.equals(this.description, order.description) &&
        Objects.equals(this.sizeFit, order.sizeFit) &&
        Objects.equals(this.requestType, order.requestType) &&
        Objects.equals(this.deliveryType, order.deliveryType) &&
        Objects.equals(this.ownerid, order.ownerid) &&
        Objects.equals(this.ownerType, order.ownerType) &&
        Objects.equals(this.pickupName, order.pickupName) &&
        Objects.equals(this.pickupPhonenumber, order.pickupPhonenumber) &&
        Objects.equals(this.pickupEmail, order.pickupEmail) &&
        Objects.equals(this.recipientName, order.recipientName) &&
        Objects.equals(this.recipientPhonenumber, order.recipientPhonenumber) &&
        Objects.equals(this.recipientEmail, order.recipientEmail) &&
        Objects.equals(this.source, order.source) &&
        Objects.equals(this.paymentStatus, order.paymentStatus) &&
        Objects.equals(this.deliveryStatus, order.deliveryStatus) &&
        Objects.equals(this.status, order.status) &&
        Objects.equals(this.userDeliveryStatus, order.userDeliveryStatus) &&
        Objects.equals(this.ratingMessage, order.ratingMessage) &&
        Objects.equals(this.dropbuddyId, order.dropbuddyId) &&
        Objects.equals(this.promoCode, order.promoCode) &&
        Objects.equals(this.valueOfItem, order.valueOfItem) &&
        Objects.equals(this.rating, order.rating) &&
        Objects.equals(this.dropoffTime, order.dropoffTime) &&
        Objects.equals(this.pickupTime, order.pickupTime) &&
        Objects.equals(this.pickupLongitude, order.pickupLongitude) &&
        Objects.equals(this.pickupLatitude, order.pickupLatitude) &&
        Objects.equals(this.id, order.id) &&
        Objects.equals(this.createdOn, order.createdOn) &&
        Objects.equals(this.updatedOn, order.updatedOn) &&
        Objects.equals(this.acceptedOn, order.acceptedOn) &&
        Objects.equals(this.selectDropBuddy, order.selectDropBuddy) &&
        Objects.equals(this.allowPriceSuggestion, order.allowPriceSuggestion) &&
        Objects.equals(this.cancelledOn, order.cancelledOn) &&
        Objects.equals(this.quantity, order.quantity) &&
        Objects.equals(this.suggestedPrice, order.suggestedPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueId, pickupAddress, dropoffAddress, pickupLocation, dropoffLocation, itemType, description, sizeFit, requestType, deliveryType, ownerid, ownerType, pickupName, pickupPhonenumber, pickupEmail, recipientName, recipientPhonenumber, recipientEmail, source, paymentStatus, deliveryStatus, status, userDeliveryStatus, ratingMessage, dropbuddyId, promoCode, valueOfItem, rating, dropoffTime, pickupTime, pickupLongitude, pickupLatitude, id, createdOn, updatedOn, acceptedOn, selectDropBuddy, allowPriceSuggestion, cancelledOn, quantity, suggestedPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    pickupAddress: ").append(toIndentedString(pickupAddress)).append("\n");
    sb.append("    dropoffAddress: ").append(toIndentedString(dropoffAddress)).append("\n");
    sb.append("    pickupLocation: ").append(toIndentedString(pickupLocation)).append("\n");
    sb.append("    dropoffLocation: ").append(toIndentedString(dropoffLocation)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sizeFit: ").append(toIndentedString(sizeFit)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    ownerid: ").append(toIndentedString(ownerid)).append("\n");
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    pickupName: ").append(toIndentedString(pickupName)).append("\n");
    sb.append("    pickupPhonenumber: ").append(toIndentedString(pickupPhonenumber)).append("\n");
    sb.append("    pickupEmail: ").append(toIndentedString(pickupEmail)).append("\n");
    sb.append("    recipientName: ").append(toIndentedString(recipientName)).append("\n");
    sb.append("    recipientPhonenumber: ").append(toIndentedString(recipientPhonenumber)).append("\n");
    sb.append("    recipientEmail: ").append(toIndentedString(recipientEmail)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userDeliveryStatus: ").append(toIndentedString(userDeliveryStatus)).append("\n");
    sb.append("    ratingMessage: ").append(toIndentedString(ratingMessage)).append("\n");
    sb.append("    dropbuddyId: ").append(toIndentedString(dropbuddyId)).append("\n");
    sb.append("    promoCode: ").append(toIndentedString(promoCode)).append("\n");
    sb.append("    valueOfItem: ").append(toIndentedString(valueOfItem)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    dropoffTime: ").append(toIndentedString(dropoffTime)).append("\n");
    sb.append("    pickupTime: ").append(toIndentedString(pickupTime)).append("\n");
    sb.append("    pickupLongitude: ").append(toIndentedString(pickupLongitude)).append("\n");
    sb.append("    pickupLatitude: ").append(toIndentedString(pickupLatitude)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    acceptedOn: ").append(toIndentedString(acceptedOn)).append("\n");
    sb.append("    selectDropBuddy: ").append(toIndentedString(selectDropBuddy)).append("\n");
    sb.append("    allowPriceSuggestion: ").append(toIndentedString(allowPriceSuggestion)).append("\n");
    sb.append("    cancelledOn: ").append(toIndentedString(cancelledOn)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    suggestedPrice: ").append(toIndentedString(suggestedPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

