/**
 * DropBuddies API
 * An API for Dropbuddies on-demand delivery service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@dropbuddies.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.dropbuddies.core.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Payment
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T00:00:58.629+01:00")
public class Payment   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("created_on")
  private Long createdOn = null;

  @SerializedName("updated_on")
  private Long updatedOn = null;

  @SerializedName("completed_on")
  private Long completedOn = null;

  @SerializedName("total_payment")
  private Double totalPayment = null;

  @SerializedName("real_cost")
  private Double realCost = null;

  @SerializedName("has_promo")
  private Integer hasPromo = null;

  @SerializedName("transaction_id")
  private String transactionId = null;

  @SerializedName("reference")
  private String reference = null;

  @SerializedName("payment_handler")
  private String paymentHandler = null;

  @SerializedName("ownerid")
  private String ownerid = null;

  @SerializedName("owner_type")
  private String ownerType = null;

  @SerializedName("user_identifier")
  private String userIdentifier = null;

  @SerializedName("user_type")
  private String userType = null;

  @SerializedName("payment_method")
  private String paymentMethod = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("promo_code")
  private String promoCode = null;

  public Payment id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Payment createdOn(Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Long createdOn) {
    this.createdOn = createdOn;
  }

  public Payment updatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Get updatedOn
   * @return updatedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
  }

  public Payment completedOn(Long completedOn) {
    this.completedOn = completedOn;
    return this;
  }

   /**
   * Get completedOn
   * @return completedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCompletedOn() {
    return completedOn;
  }

  public void setCompletedOn(Long completedOn) {
    this.completedOn = completedOn;
  }

  public Payment totalPayment(Double totalPayment) {
    this.totalPayment = totalPayment;
    return this;
  }

   /**
   * Get totalPayment
   * @return totalPayment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalPayment() {
    return totalPayment;
  }

  public void setTotalPayment(Double totalPayment) {
    this.totalPayment = totalPayment;
  }

  public Payment realCost(Double realCost) {
    this.realCost = realCost;
    return this;
  }

   /**
   * Get realCost
   * @return realCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getRealCost() {
    return realCost;
  }

  public void setRealCost(Double realCost) {
    this.realCost = realCost;
  }

  public Payment hasPromo(Integer hasPromo) {
    this.hasPromo = hasPromo;
    return this;
  }

   /**
   * Get hasPromo
   * @return hasPromo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHasPromo() {
    return hasPromo;
  }

  public void setHasPromo(Integer hasPromo) {
    this.hasPromo = hasPromo;
  }

  public Payment transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public Payment reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public Payment paymentHandler(String paymentHandler) {
    this.paymentHandler = paymentHandler;
    return this;
  }

   /**
   * Get paymentHandler
   * @return paymentHandler
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPaymentHandler() {
    return paymentHandler;
  }

  public void setPaymentHandler(String paymentHandler) {
    this.paymentHandler = paymentHandler;
  }

  public Payment ownerid(String ownerid) {
    this.ownerid = ownerid;
    return this;
  }

   /**
   * Get ownerid
   * @return ownerid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerid() {
    return ownerid;
  }

  public void setOwnerid(String ownerid) {
    this.ownerid = ownerid;
  }

  public Payment ownerType(String ownerType) {
    this.ownerType = ownerType;
    return this;
  }

   /**
   * Get ownerType
   * @return ownerType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerType() {
    return ownerType;
  }

  public void setOwnerType(String ownerType) {
    this.ownerType = ownerType;
  }

  public Payment userIdentifier(String userIdentifier) {
    this.userIdentifier = userIdentifier;
    return this;
  }

   /**
   * Get userIdentifier
   * @return userIdentifier
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserIdentifier() {
    return userIdentifier;
  }

  public void setUserIdentifier(String userIdentifier) {
    this.userIdentifier = userIdentifier;
  }

  public Payment userType(String userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  public Payment paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public Payment description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Payment currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Payment promoCode(String promoCode) {
    this.promoCode = promoCode;
    return this;
  }

   /**
   * Get promoCode
   * @return promoCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPromoCode() {
    return promoCode;
  }

  public void setPromoCode(String promoCode) {
    this.promoCode = promoCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.id, payment.id) &&
        Objects.equals(this.createdOn, payment.createdOn) &&
        Objects.equals(this.updatedOn, payment.updatedOn) &&
        Objects.equals(this.completedOn, payment.completedOn) &&
        Objects.equals(this.totalPayment, payment.totalPayment) &&
        Objects.equals(this.realCost, payment.realCost) &&
        Objects.equals(this.hasPromo, payment.hasPromo) &&
        Objects.equals(this.transactionId, payment.transactionId) &&
        Objects.equals(this.reference, payment.reference) &&
        Objects.equals(this.paymentHandler, payment.paymentHandler) &&
        Objects.equals(this.ownerid, payment.ownerid) &&
        Objects.equals(this.ownerType, payment.ownerType) &&
        Objects.equals(this.userIdentifier, payment.userIdentifier) &&
        Objects.equals(this.userType, payment.userType) &&
        Objects.equals(this.paymentMethod, payment.paymentMethod) &&
        Objects.equals(this.description, payment.description) &&
        Objects.equals(this.currency, payment.currency) &&
        Objects.equals(this.promoCode, payment.promoCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdOn, updatedOn, completedOn, totalPayment, realCost, hasPromo, transactionId, reference, paymentHandler, ownerid, ownerType, userIdentifier, userType, paymentMethod, description, currency, promoCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    totalPayment: ").append(toIndentedString(totalPayment)).append("\n");
    sb.append("    realCost: ").append(toIndentedString(realCost)).append("\n");
    sb.append("    hasPromo: ").append(toIndentedString(hasPromo)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    paymentHandler: ").append(toIndentedString(paymentHandler)).append("\n");
    sb.append("    ownerid: ").append(toIndentedString(ownerid)).append("\n");
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    userIdentifier: ").append(toIndentedString(userIdentifier)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    promoCode: ").append(toIndentedString(promoCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

