/**
 * DropBuddies API
 * An API for Dropbuddies on-demand delivery service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@dropbuddies.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.dropbuddies.core.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Promos
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-10T00:00:58.629+01:00")
public class Promos   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("created_on")
  private Long createdOn = null;

  @SerializedName("updated_on")
  private Long updatedOn = null;

  @SerializedName("expires_on")
  private Long expiresOn = null;

  @SerializedName("total_available")
  private Long totalAvailable = null;

  @SerializedName("total_consumed")
  private Long totalConsumed = null;

  @SerializedName("promo_code")
  private String promoCode = null;

  @SerializedName("ownerid")
  private String ownerid = null;

  @SerializedName("owner_type")
  private String ownerType = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("value_type")
  private String valueType = null;

  @SerializedName("value")
  private Double value = null;

  public Promos id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Promos createdOn(Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Long createdOn) {
    this.createdOn = createdOn;
  }

  public Promos updatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * Get updatedOn
   * @return updatedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(Long updatedOn) {
    this.updatedOn = updatedOn;
  }

  public Promos expiresOn(Long expiresOn) {
    this.expiresOn = expiresOn;
    return this;
  }

   /**
   * Get expiresOn
   * @return expiresOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getExpiresOn() {
    return expiresOn;
  }

  public void setExpiresOn(Long expiresOn) {
    this.expiresOn = expiresOn;
  }

  public Promos totalAvailable(Long totalAvailable) {
    this.totalAvailable = totalAvailable;
    return this;
  }

   /**
   * Get totalAvailable
   * @return totalAvailable
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalAvailable() {
    return totalAvailable;
  }

  public void setTotalAvailable(Long totalAvailable) {
    this.totalAvailable = totalAvailable;
  }

  public Promos totalConsumed(Long totalConsumed) {
    this.totalConsumed = totalConsumed;
    return this;
  }

   /**
   * Get totalConsumed
   * @return totalConsumed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalConsumed() {
    return totalConsumed;
  }

  public void setTotalConsumed(Long totalConsumed) {
    this.totalConsumed = totalConsumed;
  }

  public Promos promoCode(String promoCode) {
    this.promoCode = promoCode;
    return this;
  }

   /**
   * Get promoCode
   * @return promoCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPromoCode() {
    return promoCode;
  }

  public void setPromoCode(String promoCode) {
    this.promoCode = promoCode;
  }

  public Promos ownerid(String ownerid) {
    this.ownerid = ownerid;
    return this;
  }

   /**
   * Get ownerid
   * @return ownerid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerid() {
    return ownerid;
  }

  public void setOwnerid(String ownerid) {
    this.ownerid = ownerid;
  }

  public Promos ownerType(String ownerType) {
    this.ownerType = ownerType;
    return this;
  }

   /**
   * Get ownerType
   * @return ownerType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOwnerType() {
    return ownerType;
  }

  public void setOwnerType(String ownerType) {
    this.ownerType = ownerType;
  }

  public Promos state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Promos valueType(String valueType) {
    this.valueType = valueType;
    return this;
  }

   /**
   * Get valueType
   * @return valueType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValueType() {
    return valueType;
  }

  public void setValueType(String valueType) {
    this.valueType = valueType;
  }

  public Promos value(Double value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getValue() {
    return value;
  }

  public void setValue(Double value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Promos promos = (Promos) o;
    return Objects.equals(this.id, promos.id) &&
        Objects.equals(this.createdOn, promos.createdOn) &&
        Objects.equals(this.updatedOn, promos.updatedOn) &&
        Objects.equals(this.expiresOn, promos.expiresOn) &&
        Objects.equals(this.totalAvailable, promos.totalAvailable) &&
        Objects.equals(this.totalConsumed, promos.totalConsumed) &&
        Objects.equals(this.promoCode, promos.promoCode) &&
        Objects.equals(this.ownerid, promos.ownerid) &&
        Objects.equals(this.ownerType, promos.ownerType) &&
        Objects.equals(this.state, promos.state) &&
        Objects.equals(this.valueType, promos.valueType) &&
        Objects.equals(this.value, promos.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdOn, updatedOn, expiresOn, totalAvailable, totalConsumed, promoCode, ownerid, ownerType, state, valueType, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Promos {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    expiresOn: ").append(toIndentedString(expiresOn)).append("\n");
    sb.append("    totalAvailable: ").append(toIndentedString(totalAvailable)).append("\n");
    sb.append("    totalConsumed: ").append(toIndentedString(totalConsumed)).append("\n");
    sb.append("    promoCode: ").append(toIndentedString(promoCode)).append("\n");
    sb.append("    ownerid: ").append(toIndentedString(ownerid)).append("\n");
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    valueType: ").append(toIndentedString(valueType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

